import React from "react"
import { useStaticQuery, graphql } from "gatsby"

const Header = () => {
  // const data = useStaticQuery(getData)
  // console.log(data)
  const {
    site: {
      // siteMetadata: {
      info: {
        title,
        person: { name },
      },
    },
  } = useStaticQuery(getData)
  return (
    <div>
      {/* <h1>title: {data.site.siteMetadata.title}</h1> */}
      {/* <h1>name: {data.site.siteMetadata.person.name}</h1> */}
      <h1>title: {title}</h1>
      <h1>name: {name}</h1>
    </div>
  )
}

const getData = graphql`
  query FirstQuery {
    site {
      buildTime
      info: siteMetadata {
        title
        description
        author
        data
        person {
          name
          age
        }
      }
    }
  }
`

export default Header

// // GENERATED BY [GraphiQL]
// import React from "react"
// import { useStaticQuery, graphql } from "gatsby"

// const ComponentName = () => {
//   const data = useStaticQuery(graphql`
//     {
//       site {
//         buildTime
//         siteMetadata {
//           title
//           description
//           author
//           data
//           person {
//             name
//             age
//           }
//         }
//       }
//     }
//   `)
//   return (
//     <div>
//       <h2>name: {data.site.siteMetadata.person.name}</h2>
//       <h2>age: {data.site.siteMetadata.person.age}</h2>
//       <pre>{JSON.stringify(data, null, 2)}</pre>
//     </div>
//   )
// }

// export default ComponentName
